#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Smart Fundis: one-time account setup (planning/prompts/00-setup-once.md).
# This wizard captures NO values. Every key stays in the provider dashboard (or
# your password manager) until V0 wires them in. Run it in Git Bash from the
# repo root:  bash scripts/wizards/00-setup-once.sh

TOTAL_STAGES=7

banner "Smart Fundis: one-time account setup"

stage "Clerk: create the application"
say "Clerk handles sign-in (ADR-16: email + Google). Start with a development instance."
open_url "https://dashboard.clerk.com/"
step "Sign in (or sign up), then click 'Create application'."
step "Name it 'Smart Fundis'."
step "Under sign-in options, turn on Email and Google. Leave the others off."
step "Click 'Create application'. It opens on the development instance, so keep it there."
note "Phone numbers are collected in onboarding (V3), not used for sign-in."
pause "Done? The app exists with Email and Google on. Press Enter"

stage "Clerk: activate the Convex integration"
say "This lets Convex accept Clerk tokens. Clerk now does it from one page."
open_url "https://dashboard.clerk.com/apps/setup/convex"
step "Pick the 'Smart Fundis' app if asked, then click 'Activate Convex integration'."
step "It shows your Frontend API URL (https://<words>.clerk.accounts.dev). Don't copy it now, because V0 needs it."
step "Then go to Configure → JWT templates. If a template named 'convex' is there, open it."
step "Make sure its claims include email, email_verified and name. If any are missing, add them:"
note '    "email": "{{user.primary_email_address}}",'
note '    "email_verified": "{{user.email_verified}}",'
note '    "name": "{{user.full_name}}"'
warn "If the page looks different from this, stop and tell Claude what you see. Don't guess."
pause "Done? The integration is active and the claims are checked. Press Enter"

stage "Convex: account and team"
say "Convex is the system of record. V0's 'npx convex dev' creates the project itself."
open_url "https://dashboard.convex.dev/"
step "Sign in with GitHub (as simpleHacker0893, the same account as the repo)."
step "Create or pick the team the project will live in. Don't create a project yet."
note "Where it's set in V0: CLERK_FRONTEND_API_URL, ADMIN_EMAILS and AI_SHARED_SECRET (dev and prod separately)."
pause "Done? You're signed in and the team exists. Press Enter"

stage "Vercel: account and GitHub connection"
say "Vercel hosts web/. The import (root directory web/) happens in V0, once web/ exists."
open_url "https://vercel.com/signup"
step "Sign in with GitHub (simpleHacker0893)."
step "Open Account Settings → Authentication (or Login Connections) and check that GitHub is connected."
step "Don't import the repo yet: web/ doesn't exist, so the build would fail."
pause "Done? Vercel is linked to GitHub. Press Enter"

stage "NVIDIA: build.nvidia.com API key (lane B)"
say "Nemotron runs through the hosted NVIDIA API. The key lives only on the Brev box (V2)."
open_url "https://build.nvidia.com/"
step "Sign in (or create an NVIDIA account)."
step "Open any model page (search 'nemotron') and click 'Get API Key', or use your profile → API Keys."
step "Generate a key and save it in your PASSWORD MANAGER as NVIDIA_API_KEY."
warn "Never paste it into this repo, a chat, or an issue."
pause "Done? The key is saved in your password manager. Press Enter"

stage "LangSmith: API key (lane B)"
say "LangSmith traces the AI pipeline, with inputs and outputs masked (ADR-13). Brev only."
open_url "https://smith.langchain.com/"
step "Sign in, then go to Settings → API Keys → Create API Key."
step "Save it in your PASSWORD MANAGER as LANGSMITH_API_KEY."
pause "Done? The key is saved in your password manager. Press Enter"

stage "Hugging Face: Cosmos-Reason2 licence (lane B)"
say "vLLM on Brev downloads Cosmos-Reason2. The licence has to be accepted first."
open_url "https://huggingface.co/nvidia/Cosmos-Reason2-8B"
step "Sign in, then accept the licence / access terms on the 8B model page."
open_url "https://huggingface.co/nvidia/Cosmos-Reason2-2B"
step "Accept it on the 2B model page too (the fallback, ADR-12)."
step "Settings → Access Tokens → create a READ token. Save it in your PASSWORD MANAGER as HF_TOKEN."
warn "If a model URL 404s, search huggingface.co/nvidia for 'Cosmos-Reason2' and tell Claude the exact names."
pause "Done? Both licences are accepted and the token is saved. Press Enter"

finish
say "Nothing was written to disk and no secrets were set: that's intended."
say "Paste this back to Claude: 'wizard done: Clerk, Convex, Vercel, NVIDIA, LangSmith, HF'"
say "and mention any stage that didn't match what you saw."
printf '\n'
