#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# The V1 human checks (#43): a real-phone upload on Android Chrome and iOS
# Safari, recorded in docs/reviews/V1.md. This wizard reads and writes no
# secrets and never touches .env: _existing() looks for this path, which does
# not exist, so `ask` never offers a stored default.
ENV_FILE="docs/reviews/.no-env-for-this-wizard"
REVIEW_FILE="docs/reviews/V1.md"

[[ -d .git && -d convex && -d web ]] || { printf 'Run this from the repo root.\n'; exit 1; }

# result KEY "Question": asks pass / fail / skip and stores it in KEY.
result() {
  local key="$1" question="$2" reply=""
  while :; do
    printf '  %s%s%s [p]ass / [f]ail / [s]kip: ' "$BOLD" "$question" "$RESET"
    read -r reply || true
    case "$reply" in
      p|P) printf -v "$key" '%s' "✅ pass"; return ;;
      f|F) printf -v "$key" '%s' "❌ fail"; return ;;
      s|S) printf -v "$key" '%s' "⏭ skipped"; return ;;
    esac
  done
}

TOTAL_STAGES=7

banner "V1 real-phone check (#43)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Get the loop running on dev"
say "The phone test needs the dev backend, the stub worker and a web URL your phone can open."
step "Convex dev deployment: modest-warbler-906. AI_STUB_ENABLED=1 is already set there (dev only)."
step "Terminal A, from ai-service/:  uv run python scripts/stub_worker.py --poll-interval 3"
note "It prints 'claimed Assessment …' lines as uploads arrive. Keep it running."
step "Have a SECOND account seeded as an Expert for Electrical (not the phone's Fundi account)."
note "  Git Bash:   pnpm exec convex run seed:expert '{\"email\":\"expert@example.com\"}'"
note "  PowerShell: pnpm exec convex run seed:expert '{\\\"email\\\":\\\"expert@example.com\\\"}'"
say ""
say "How will the phone reach the app?"
step "a) a Vercel preview, only if its NEXT_PUBLIC_CONVEX_URL points at the DEV deployment, or"
step "b) your PC on the same Wi-Fi: pnpm --filter @smart-fundis/web dev -H 0.0.0.0, then http://<your-PC-IP>:3000"
note "   Find the IP with ipconfig; allow Node through Windows Firewall if the phone can't connect."
ask APP_URL "Paste the URL you'll open on the phones:"
pause "Stub worker running and Expert account ready? Press Enter"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Android Chrome: sign in and pick the Task"
step "On the Android phone, open Chrome at: $APP_URL"
step "Sign in (or sign up) with the phone's Fundi account; finish onboarding if asked."
step "Open /fundi, pick Electrical, then Install a 13A socket, read the tips, then 'Next: get my code'."
note "Note the 3-digit Liveness code on screen: the video must show it."
ask ANDROID_DEVICE "Phone model, Android version and Chrome version (e.g. Tecno Spark 10, Android 13, Chrome 129):"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Android Chrome: record, consent, upload"
step "Tap the record option. The camera should open."
step "Record 10 to 90 s showing the Liveness code, then keep the video."
step "Open 'Verification consent', read it, close it, and tick the box. Upload stays disabled until it's ticked."
step "Tap Upload and watch the progress bar."
step "Without refreshing, the status goes: Waiting in line, then The AI is watching your video, then Awaiting expert review."
note "The stub decides by file name; a camera clip gets an automatic name, so expect the 'pass' path."
result ANDROID_UPLOAD "Did the upload show progress and reach 'Awaiting expert review' with no refresh?"
ask ANDROID_NOTES "Notes (errors, slow steps, anything odd; Enter for none):"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "iOS Safari: the same upload"
say "If no iPhone is available, choose skip and give the reason."
step "On the iPhone, open Safari at: $APP_URL and sign in with a Fundi account."
step "/fundi, Electrical, Install a 13A socket, get the code, record with the camera."
step "Consent, tick, Upload, and watch it reach 'Awaiting expert review' without a refresh."
result IOS_UPLOAD "Did the iOS Safari upload work the same way?"
ask IOS_DEVICE "iPhone model and iOS version, or why it was skipped:"
ask IOS_NOTES "Notes (Enter for none):"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Close the loop: the Expert approves, the Badge shows"
step "On a computer, sign in as the Expert account and open $APP_URL/expert"
step "Open the phone upload: the video plays, the Liveness code and Observations show, the AI suggestion is labelled."
step "Approve it."
step "On the phone, /fundi shows: Verified by Smart Fundis — Electrical: Install a 13A socket · <date>"
step "On the phone, open the Fundi's public profile /f/<id> and check the same Badge line, with no phone, video or AI output."
result LOOP_BADGE "Did approval show the Badge on /fundi and on /f/[id] on the phone?"
ask LOOP_NOTES "Notes (Enter for none):"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Kiswahili check: not applicable (D-64)"
say "The ticket asked a native speaker to sign off the Kiswahili consent (R-20)."
say "Since D-64 (2026-09-26) the app is English only, consent included (accepted risk R-44)."
say "So V1 has no Kiswahili text to check; the check moves to the Kiswahili phase."
if confirm "Record the Kiswahili check as not applicable under D-64?"; then
  SW_CHECK="⏭ not applicable: English only under D-64 (accepted risk R-44); the native-speaker check (R-20) moves to the Kiswahili phase"
else
  ask SW_CHECK "What should be recorded for the Kiswahili check instead?"
fi
ask CHECKED_BY "Who ran these checks (name or GitHub handle)?"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Record the results in $REVIEW_FILE"
TODAY=$(date +%Y-%m-%d)
say "Android: $ANDROID_UPLOAD · iOS: $IOS_UPLOAD · loop and Badge: $LOOP_BADGE"
if confirm "Append these results to $REVIEW_FILE?"; then
  [[ -f "$REVIEW_FILE" ]] || printf '# V1 review\n' > "$REVIEW_FILE"
  {
    printf '\n## Human checks (#43), %s\n\n' "$TODAY"
    printf -- '- **Checked by:** %s\n' "$CHECKED_BY"
    printf -- '- **App URL:** %s\n' "$APP_URL"
    printf -- '- **Backend:** Convex dev deployment `modest-warbler-906`, with the stub worker (#40)\n\n'
    printf '| Check | Result | Device | Notes |\n| --- | --- | --- | --- |\n'
    printf '| Android Chrome: record, consent, upload with progress, `awaiting_review` with no refresh | %s | %s | %s |\n' "$ANDROID_UPLOAD" "$ANDROID_DEVICE" "${ANDROID_NOTES:-—}"
    printf '| iOS Safari: the same | %s | %s | %s |\n' "$IOS_UPLOAD" "$IOS_DEVICE" "${IOS_NOTES:-—}"
    printf '| Expert approves; the Badge shows on `/fundi` and `/f/[id]` | %s | desktop and phone | %s |\n' "$LOOP_BADGE" "${LOOP_NOTES:-—}"
    printf '| Kiswahili consent and status strings (R-20) | %s | — | — |\n' "$SW_CHECK"
  } >> "$REVIEW_FILE"
  printf '  %s✓ appended%s to %s\n' "$GREEN" "$RESET" "$REVIEW_FILE"
else
  SKIPPED+=("results not written to $REVIEW_FILE")
fi

finish
say "Next: tell Claude the checks are done; it commits $REVIEW_FILE on v1/43-real-phone-check and opens the PR."
